# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20170607_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['date_modified']},
        ),
    ]
